def getDiseaseFromIndex(crop , index):
    obj = {
        'Mango' : {
            0 : ["Anthracnose" , "Anthracnose is a fungal disease that typically causes dark lesions on leaves. Many plants are susceptible to this disease including trees, perennial shrubs, vegetables, fruit, and flowers. Anthracnose is worse in cool, wet weather and when irrigation splashes foliage.","To cure anthracnose in mango, regularly prune trees and remove infected plant parts. Spray fungicides like copper oxychloride (0.3%) or carbendazim (0.1%) during flowering and fruiting. Use biological agents like *Trichoderma harzianum* to suppress the fungus. Post-harvest, dip fruits in hot water (52°C for 5 minutes) to prevent storage rot."],
            1 : ['Bacterial Canker',"Bacterial canker, one of the most important sweet and sour cherry pathogens, is caused by two different pathogens, Pseudomonas syringae and P. morsprunorum, and is characterized by oozing of gum (gummosis) at infection sites. Disease development is most prevalent during the cool, wet periods of early spring.","To manage bacterial canker, prune and destroy all infected branches and twigs, and disinfect pruning tools after each use. Spray copper oxychloride at 0.3% mixed with streptocycline at 100 ppm every 15 days during the active season. Maintain orchard hygiene and avoid wounding trees during operations."],
            2 : ['Cutting Weevil',"Adult weevils scrape the surface layers of mango leaves which turn brown, crumple and become contorted. They also cut windowpanes between the veins. The most obvious sign of infestation is the presence of cut leaves on the ground beneath the tree, and the stripped, leaf-less shoots, which can be seen from a distance.","Remove and burn infested shoots to eliminate the weevils' breeding sites. Spray insecticides like dimethoate (0.05%) or imidacloprid (0.003%) on tender shoots where infestation is observed. Regular pruning and maintaining cleanliness in the orchard help reduce pest incidence."],
            3 : ['Die Back',"As the veins turn brown, leaves curl upwards and eventually fall off the tree. In the final stages of dieback, twigs and branches secrete gum. Initially, small gum droplets become visible, but as the disease progresses the entire branch or trunk may be covered.","Cut and remove infected branches at least 10–15 cm below the affected area. Apply Bordeaux paste on the cut surfaces to prevent further spread. Spray copper-based fungicides such as copper oxychloride (0.3%) during the monsoon and post-monsoon periods to control the disease."],
            4 : ['Gall Midge',"Mango gall midge are tiny flies widespread in most mango growing areas of the world. Gall midge larvae feed within plant tissue, causing abnormal plant growth called galls that can damage to mango leaves, flowers, fruit and shoots.","Destroy all affected shoots and buds showing signs of gall formation. Spray insecticides such as lambda-cyhalothrin or dimethoate (0.05%) during the emergence of new vegetative or floral flush. Keeping the orchard clean and free of weeds supports effective control."],
            5 : ['Healthy',"HEALTHY","No solution required"],
            6 : ['Powdery Mildew',"Oidium mangiferae Berthet (a fungus), causing powdery mildew of mango, is widely distributed throughout the Mango cultivated areas. It infects panicles, fruits, and leaves. Mango is the only known host of the mango powdery mildew pathogen.","Apply wettable sulfur (0.2%) or systemic fungicides like hexaconazole or dinocap at the first sign of the disease. Repeat sprays at 10–15 day intervals if conditions remain favorable for disease development. Ensure good ventilation in the canopy by proper pruning."],
            7: ['Sooty Mould',"Mango sooty mold (Meliola mangiferae) is one of the species of fungi that grow on honeydew results from interactions among sap-feeding insects such as soft scale.","Spray neem oil (1–2%) or wash the affected leaves with a mild soap solution to remove the mould. Control sap-sucking insects such as aphids, mealybugs, and scales using imidacloprid (0.003%). Prune the trees to allow sunlight and airflow for quicker drying and mould suppression."]
        },
        'Coffee' : {
            0: ['Cerscospora',"Cercospora disease is a very important disease of Coffee which results in yield loss and damage to the nursery plants in early stage of growth and later emerges a brown eye spot.","Spray copper oxychloride (0.3%) or chlorothalonil every 15–20 days during humid weather to control Cercospora. Proper shade management and avoiding excess nitrogen fertilization help reduce disease pressure. Additionally, remove and destroy infected fallen leaves to minimize sources of infection."], 
            1 : ['Healthy', "HEALTHY","No solution required"],
            2 : ['Leaf rust' ,"s the leaf spots grow, they may come together or blend to form bigger spots. The leaves form large irregular shapes or lesions. They eventually dry up and turn brown. The symptoms may vary depending on a variety of factors. These include the environment, farm practices and the sensitivity of the plant to disease. Spots mostly begin to form at the leaf edges or tips where water collects.","Control leaf rust by applying Bordeaux mixture (1%) or systemic fungicides like hexaconazole before the rainy season. Using rust-resistant coffee varieties and maintaining good shade management can also lower disease severity. Balanced fertilization improves plant health and reduces susceptibility."],
            3 : ['Miner' , "Always consider an integrated approach along with preventive measures and available biological treatments. Currently, coffee growers use neurotoxic insecticides, such as organophosphates, carbamates, pyrethroids, neonicotinoids, and diamides.","Prune and destroy infested leaves and spray insecticides such as chlorpyrifos (0.05%) or neem oil to manage leaf miner populations. Introducing natural predators like Prorops nasuta provides biological control. Repeat sprays during peak infestation periods for effective management."],
            4 : [ 'Phoma' , "The conilon coffee crop (Coffea canephora Pierre ex Froehner) imposes constant challenges on rural producers to make the productive process possible with a sustainable agricultural development and quality product to meet the increasingly demanding consumer markets.","To control Phoma disease, prune and burn infected branches, and apply Bordeaux paste on cut surfaces. Follow up with copper oxychloride (0.3%) sprays after pruning. Improving drainage and reducing excessive shade help create unfavorable conditions for the fungus."]
        },
        'Corn' : {
            0 :    ['Common Rust' , "Common rust is caused by the fungus Puccinia sorghi. Late occurring infections have limited impact on yield. The fungus overwinters on plants in southern states and airborne spores are wind-blown to northern states during the growing season."],
            1 :   ['Gray Leaf spot',"Gray leaf spot is typically the most serious foliar disease of corn in the U.S. corn belt, although other diseases can be more important in areas and years where weather conditions do not favor gray leaf spot. "],
            2 :   ['healthy',"HEALTHY","No solution required"],
            3 :   ['northern leaf blight',"Northern corn leaf blight is favored by wet humid cool weather typically found later in the growing season. Spores of the fungus that causes this disease can be transported by wind long distances from infected fields. Spread within and between fields locally also relies on wind blown spores."]
        },
        'Rice' : {
            0 : ['Bacterialblight' , "Primarily the plant is light green to greyish green and water-soaked streaks appear on the leaves but once it gets affected by the bacterial blight, they form larger yellowish lesions with uneven edges. Further, the leaves become yellow, gradually wilt and die.","Use resistant rice varieties and avoid excessive nitrogen fertilizer, ensure proper field drainage and sanitation to reduce bacterial spread, apply copper-based bactericides if symptoms are detected early."],
            1 : ['Blast' , "Blast is caused by the fungus Magnaporthe oryzae. It can affect all above ground parts of a rice plant: leaf, collar, node, neck, parts of panicle, and sometimes leaf sheath.","Grow blast-resistant varieties and maintain adequate plant spacing, apply fungicides like tricyclazole during early stages of infection, avoid water stress and manage nitrogen levels carefully."],
            2 : ['Brownspot' , "Brown spot disease in rice is caused by the fungus Cochliobolus miyabeanus (originally Helminthosporium oryzae). Sesame leaf spot, Helminthosporiose, or fungal blight are all names for a brown spot. ","Use disease-free seeds and apply balanced fertilizers, especially potassium. Improve field drainage and practice crop rotation to reduce pathogen buildup. Apply fungicides like mancozeb if disease severity increases."],
            3 : ['Tungro' , "Plants affected by tungro exhibit stunting and reduced tillering. Leaves become yellow or orange-yellow, it may also have rust-colored spots. Yellowing starts from the tip of the leaf and may extend to the lower part of the leaf blade. Third leaf from the top most infected plants is taller than other leaves.","Plant resistant varieties and control green leafhopper vectors using insecticides. Remove and destroy infected plants early to prevent further spread. Avoid planting during peak vector activity periods and ensure proper field hygiene."]
        },
        'Wheat':{
            0 : ['Healthy' , "HEALTHY","No solution required"],
            1 : ['Brown Rust' , "Leaf rust, also known as brown rust, is caused by the fungus Puccinia triticina. This rust disease occurs wherever wheat, barley and other cereal crops are grown.","Grow rust-resistant wheat varieties to reduce infection risk. Apply fungicides such as triazoles or strobilurins at early disease stages. Practice crop rotation and remove volunteer wheat plants to limit pathogen sources."],
            2 : ['Yellow Rust' , "The characteristic symptom of yellow rust is of parallel rows of yellowish orange coloured pustules on the leaves of adult plants. Epidemics of yellow rust often start as individual plants, usually in the autumn.","Use resistant wheat cultivars and monitor fields regularly for early signs. Spray effective fungicides like azoxystrobin or propiconazole when symptoms appear. Maintain balanced fertilization and avoid dense planting to reduce disease spread."]
        }
    }
    
    return obj[crop][index]

